"""Headless Altium project COMPILE + violation dump.

Drives real Altium (X2 RunScript) to open test1.PrjPcb, run the project compiler
(IProject.DM_Compile), and write every violation (DM_Violations) to a result file
with its description text. This is (1) how we verify a fix actually cleared the
Altium compile errors it targeted, and (2) the hook for wiring Altium's compile
into review/generate (TODO B) so our lint can be cross-referenced against Altium's
own ERC.

Same launch/poll/watchdog machinery as run_altium_verify.py. Compiling can be the
slow/hangy step, so the Python-side watchdog kills X2 on timeout.

Usage:
    python -m test1.altium.verify.altium_compile [out.PrjPcb] [result.txt]
"""
from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

from ..config import OUT_DIR

TIMEOUT_S = 240
POLL_S = 3


def find_x2() -> Path | None:
    base = Path(r"C:\Program Files\Altium")
    return next(iter(sorted(base.glob("AD*/X2.EXE"), reverse=True)), None) if base.exists() else None


# DelphiScript: open + compile the project, enumerate DM_Violations, write the
# violation COUNT (reliable). IViolation's text accessor is undocumented and
# version-specific (AD26 rejects .Description/.DescriptorString/.Name at COMPILE
# time — DelphiScript validates unknown identifiers up front, so Try/Except can't
# guard them). So we don't dereference per-violation text here; the count is the
# regression signal, and the full message list comes from a manual Messages-panel
# export when the strings are actually needed. (If a confirmed IViolation text
# member is found later, add it back behind a known-good name.)
_PAS_TEMPLATE = r"""{ Generated by altium_compile.py -- do not edit by hand. }
Procedure CompileAndDump;
Var
    WS      : IWorkspace;
    Prj     : IProject;
    SL      : TStringList;
    PrjPath : String;
    ResPath : String;
    i, n    : Integer;
    ok      : LongBool;
Begin
    PrjPath := '__PRJ__';
    ResPath := '__RESULT__';
    SL := TStringList.Create;
    SL.Add('status=STARTED');
    SL.SaveToFile(ResPath);
    Try
        ResetParameters;
        AddStringParameter('ObjectKind', 'Project');
        AddStringParameter('FileName', PrjPath);
        RunProcess('WorkspaceManager:OpenObject');

        WS := GetWorkspace;
        If WS = Nil Then Begin
            SL.Clear; SL.Add('status=NO_WORKSPACE'); SL.SaveToFile(ResPath);
            Client.SendMessage('Application:Exit','',255,Client.CurrentView); Exit;
        End;
        Prj := WS.DM_FocusedProject;
        If Prj = Nil Then Prj := WS.DM_GetProjectFromPath(PrjPath);
        If Prj = Nil Then Begin
            SL.Clear; SL.Add('status=NO_PROJECT'); SL.SaveToFile(ResPath);
            Client.SendMessage('Application:Exit','',255,Client.CurrentView); Exit;
        End;

        Prj.DM_Compile;

        n := Prj.DM_ViolationCount;
        SL.Clear;
        SL.Add('status=OK');
        SL.Add('violation_count=' + IntToStr(n));
        SL.SaveToFile(ResPath);
    Except
        SL.Clear; SL.Add('status=EXCEPTION'); SL.SaveToFile(ResPath);
    End;
    SL.Free;
    Client.SendMessage('Application:Exit','',255,Client.CurrentView);
End;
"""

_PRJSCR_TEMPLATE = """[Design]
Version=1.0
HierarchyMode=Automatic

[Document1]
DocumentPath=__PASNAME__
"""

SCRIPT_STEM = "compile_dump"


def write_script(prj_pcb: Path, result: Path, work: Path) -> tuple[Path, str]:
    work.mkdir(parents=True, exist_ok=True)
    pas = work / f"{SCRIPT_STEM}.pas"
    prj = work / "compile.PrjScr"
    pas.write_text(
        _PAS_TEMPLATE
        .replace("__PRJ__", str(prj_pcb).replace("\\", "\\\\"))
        .replace("__RESULT__", str(result).replace("\\", "\\\\")),
        encoding="utf-8")
    prj.write_text(_PRJSCR_TEMPLATE.replace("__PASNAME__", pas.name), encoding="utf-8")
    return prj, f"{SCRIPT_STEM}>CompileAndDump"


def parse_status(result: Path) -> str | None:
    if not result.exists():
        return None
    for line in result.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("status="):
            return line.split("=", 1)[1].strip()
    return None


def _kill(proc: subprocess.Popen) -> None:
    if proc.poll() is None:
        try:
            proc.terminate(); time.sleep(2)
            if proc.poll() is None:
                proc.kill()
        except Exception:
            pass


def main() -> int:
    prj_pcb = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DIR / "test1.PrjPcb"
    result = Path(sys.argv[2]) if len(sys.argv) > 2 else OUT_DIR / "verify" / "compile_result.txt"
    if not prj_pcb.exists():
        print(f"FAIL: project not found: {prj_pcb}"); return 2
    x2 = find_x2()
    if x2 is None:
        print("FAIL: X2.EXE not found"); return 2
    result.parent.mkdir(parents=True, exist_ok=True)
    if result.exists():
        result.unlink()
    print(f"Altium: {x2}\nProject: {prj_pcb}\n")
    prj, proc_name = write_script(prj_pcb, result, result.parent)
    arg = f"-RScriptingSystem:RunScript(ProjectName={prj}|ProcName={proc_name})"
    print(f"Launching (timeout {TIMEOUT_S}s):\n  {x2} {arg}\n")
    proc = subprocess.Popen([str(x2), arg])
    deadline = time.time() + TIMEOUT_S
    last = None
    try:
        while time.time() < deadline:
            st = parse_status(result)
            if st != last:
                print(f"  [{int(time.time()-(deadline-TIMEOUT_S))}s] status={st}")
                last = st
            if st in ("OK", "NO_WORKSPACE", "NO_PROJECT", "EXCEPTION"):
                break
            time.sleep(POLL_S)
        else:
            print(f"\nFAIL: timed out after {TIMEOUT_S}s"); _kill(proc); return 1
    finally:
        for _ in range(15):
            if proc.poll() is not None:
                break
            time.sleep(2)
        _kill(proc)

    if not result.exists():
        print("FAIL: no result file"); return 1
    lines = result.read_text(encoding="utf-8", errors="replace").splitlines()
    st = parse_status(result)
    count_line = next((l for l in lines if l.startswith("violation_count=")), "violation_count=?")
    print(f"\nstatus={st}  {count_line}")
    print("(violation COUNT only — Altium's IViolation text accessor is undocumented;")
    print(" use a manual Messages-panel export when the message strings are needed.)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
