"""Tier 1 verification: drive REAL Altium as an oracle, unattended.

This is the automated replacement for "open it in Altium and tell me if it's
corrupt". It:

  1. reopens the .SchDoc with altium_monkey to get the EXPECTED object counts,
  2. generates a DelphiScript that opens the same file in Altium Designer,
     enumerates objects through Altium's own SCH API, writes the counts to a
     result file, and exits Altium,
  3. launches X2.EXE running that script, with a hard timeout + kill watchdog
     so a license/GUI prompt can never wedge the run,
  4. diffs Altium's counts against altium_monkey's. Match => the binary is
     genuinely Altium-valid; mismatch / no-result => corruption or parse fail.

Altium is NOT truly headless: the GUI launches, runs the script, self-closes.
Expect ~30-90s. Run on milestones, not every edit (Tier 0 smoke_test is the
fast everyday gate).

Usage:
    python -m test1.altium.verify.run_altium_verify [path\\to\\file.SchDoc]
"""

from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

from altium_monkey import AltiumSchDoc

from ..config import OUT_DIR

# Object kinds we cross-check. altium_monkey view name -> result-file key.
COUNT_KEYS = ["components", "wires", "ports", "power_ports", "net_labels", "junctions", "no_erc"]

TIMEOUT_S = 180
POLL_S = 2


def find_x2() -> Path | None:
    base = Path(r"C:\Program Files\Altium")
    if not base.exists():
        return None
    # Prefer the highest AD** build directory.
    candidates = sorted(base.glob("AD*/X2.EXE"), reverse=True)
    return candidates[0] if candidates else None


def expected_counts(schdoc: Path) -> dict[str, int]:
    """What altium_monkey says is in the file — the baseline Altium must match."""
    doc = AltiumSchDoc(schdoc)
    return {
        "components": len(doc.components),
        "wires": len(doc.wires),
        "ports": len(doc.ports),
        "power_ports": len(doc.power_ports),
        "net_labels": len(doc.net_labels),
        "junctions": len(doc.junctions),
        "no_erc": len(doc.no_ercs),
    }


_PAS_TEMPLATE = r"""{ Generated by run_altium_verify.py -- do not edit by hand. }
Procedure Verify;
Var
    Doc        : IServerDocument;
    CurrentSch : ISch_Document;
    Iterator   : ISch_Iterator;
    Obj        : ISch_GraphicalObject;
    SL         : TStringList;
    nComp, nWire, nPort, nPower, nNet, nJunc, nNoERC : Integer;
    SchPath, ResultPath : String;
Begin
    SchPath    := '__SCHDOC__';
    ResultPath := '__RESULT__';

    SL := TStringList.Create;
    SL.Add('status=STARTED');
    SL.SaveToFile(ResultPath);

    Try
        Doc := Client.OpenDocument('SCH', SchPath);
        If Doc = Nil Then
        Begin
            SL.Clear; SL.Add('status=OPEN_FAILED'); SL.SaveToFile(ResultPath);
            Client.SendMessage('Application:Exit', '', 255, Client.CurrentView);
            Exit;
        End;
        Client.ShowDocument(Doc);

        CurrentSch := SchServer.GetSchDocumentByPath(SchPath);
        If CurrentSch = Nil Then CurrentSch := SchServer.GetCurrentSchDocument;
        If CurrentSch = Nil Then
        Begin
            SL.Clear; SL.Add('status=NO_SCH_DOC'); SL.SaveToFile(ResultPath);
            Client.SendMessage('Application:Exit', '', 255, Client.CurrentView);
            Exit;
        End;

        nComp := 0; nWire := 0; nPort := 0; nPower := 0; nNet := 0; nJunc := 0; nNoERC := 0;

        Iterator := CurrentSch.SchIterator_Create;
        Iterator.AddFilter_ObjectSet(MkSet(eSchComponent, eWire, ePort, ePowerObject, eNetLabel, eJunction, eNoERC));
        Obj := Iterator.FirstSchObject;
        While Obj <> Nil Do
        Begin
            Case Obj.ObjectId Of
                eSchComponent : Inc(nComp);
                eWire         : Inc(nWire);
                ePort         : Inc(nPort);
                ePowerObject  : Inc(nPower);
                eNetLabel     : Inc(nNet);
                eJunction     : Inc(nJunc);
                eNoERC        : Inc(nNoERC);
            End;
            Obj := Iterator.NextSchObject;
        End;
        CurrentSch.SchIterator_Destroy(Iterator);

        SL.Clear;
        SL.Add('status=OK');
        SL.Add('components='  + IntToStr(nComp));
        SL.Add('wires='       + IntToStr(nWire));
        SL.Add('ports='       + IntToStr(nPort));
        SL.Add('power_ports=' + IntToStr(nPower));
        SL.Add('net_labels='  + IntToStr(nNet));
        SL.Add('junctions='   + IntToStr(nJunc));
        SL.Add('no_erc='      + IntToStr(nNoERC));
        SL.SaveToFile(ResultPath);
    Except
        SL.Clear; SL.Add('status=EXCEPTION'); SL.SaveToFile(ResultPath);
    End;

    SL.Free;
    Client.SendMessage('Application:Exit', '', 255, Client.CurrentView);
End;
"""


# AD26's RunScript will not load a bare .pas via FileName=; it needs a script
# PROJECT (.PrjScr) plus a module-qualified procedure name (Module>Proc, where
# Module is the .pas filename stem). This minimal INI-style project is enough.
_PRJSCR_TEMPLATE = """[Design]
Version=1.0
HierarchyMode=Automatic

[Document1]
DocumentPath=__PASNAME__
"""

SCRIPT_STEM = "verify_schdoc"   # -> module name used in ProcName=verify_schdoc>Verify


def write_script(schdoc: Path, result: Path, work: Path) -> tuple[Path, str]:
    """Write verify_schdoc.pas + verify.PrjScr into `work`.

    Returns (prjscr_path, proc_name) for the RunScript invocation.
    """
    work.mkdir(parents=True, exist_ok=True)
    pas = work / f"{SCRIPT_STEM}.pas"
    prj = work / "verify.PrjScr"

    pas.write_text(
        _PAS_TEMPLATE
        .replace("__SCHDOC__", str(schdoc).replace("\\", "\\\\"))
        .replace("__RESULT__", str(result).replace("\\", "\\\\")),
        encoding="utf-8",
    )
    prj.write_text(_PRJSCR_TEMPLATE.replace("__PASNAME__", pas.name), encoding="utf-8")
    return prj, f"{SCRIPT_STEM}>Verify"


def parse_result(result: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in result.read_text(encoding="utf-8").splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def main() -> int:
    schdoc = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DIR / "smoke.SchDoc"
    if not schdoc.exists():
        print(f"FAIL: schdoc not found: {schdoc}")
        return 2

    x2 = find_x2()
    if x2 is None:
        print("FAIL: X2.EXE (Altium Designer) not found under C:\\Program Files\\Altium")
        return 2
    print(f"Altium: {x2}")
    print(f"Target: {schdoc}\n")

    exp = expected_counts(schdoc)
    print("altium_monkey expects:", exp)

    work = OUT_DIR / "verify"
    result = work / "result.txt"
    if result.exists():
        result.unlink()
    prj, proc_name = write_script(schdoc, result, work)

    arg = f'-RScriptingSystem:RunScript(ProjectName={prj}|ProcName={proc_name})'
    print(f"\nLaunching (timeout {TIMEOUT_S}s):\n  {x2} {arg}\n")

    proc = subprocess.Popen([str(x2), arg])
    deadline = time.time() + TIMEOUT_S
    last_status = None
    try:
        while time.time() < deadline:
            if result.exists():
                data = parse_result(result)
                st = data.get("status")
                if st != last_status:
                    print(f"  [{int(time.time()-(deadline-TIMEOUT_S))}s] status={st}")
                    last_status = st
                if st in ("OK", "OPEN_FAILED", "NO_SCH_DOC", "EXCEPTION"):
                    break
            time.sleep(POLL_S)
        else:
            print(f"\nFAIL: timed out after {TIMEOUT_S}s (no terminal status).")
            _kill(proc)
            return 1
    finally:
        # Give Altium a moment to self-exit; kill if it lingers.
        for _ in range(15):
            if proc.poll() is not None:
                break
            time.sleep(2)
        _kill(proc)

    data = parse_result(result)
    if data.get("status") != "OK":
        print(f"\nFAIL: Altium reported status={data.get('status')!r} — file did not open cleanly.")
        return 1

    print("\nAltium reported:")
    mismatches, warnings = [], []
    for k in COUNT_KEYS:
        got = int(data.get(k, -1))
        want = exp.get(k, -1)
        ok = got == want
        # Junctions are a KNOWN upstream bug: real Altium drops altium_monkey
        # junction records on load (see FINDINGS.md). Connectivity rides
        # T-intersections, so this divergence is expected and non-fatal.
        known = (k == "junctions" and got == 0 and want > 0)
        flag = "OK " if ok else ("WARN" if known else "DIFF")
        print(f"  [{flag}] {k}: altium={got}  altium_monkey={want}"
              + ("   (known: Altium drops junctions)" if known else ""))
        if not ok:
            (warnings if known else mismatches).append(k)

    print("\n" + "=" * 52)
    if mismatches:
        print(f"Tier 1 FAILED — Altium parsed the file but counts diverge: {mismatches}")
        return 1
    if warnings:
        print(f"Tier 1 PASSED (with known warnings: {warnings}) — real Altium opened "
              f"the file; all object counts match except the known junction drop.")
        return 0
    print("Tier 1 PASSED — real Altium opened the file and object counts match.")
    return 0


def _kill(proc: subprocess.Popen) -> None:
    if proc.poll() is None:
        try:
            proc.terminate()
            time.sleep(2)
            if proc.poll() is None:
                proc.kill()
        except Exception:
            pass


if __name__ == "__main__":
    sys.exit(main())
